services:
  api:
    build:
      context: .
      dockerfile: MicroLedger.Api/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__LedgerDb=Server=host.docker.internal;Database=Ledger;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=true;
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  sqlServer :
    image : mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD="YourStrong!Passw0rd"
      - ACCEPT_EULA="Y"
    ports:
      - "1433:1433"
    restart: always


  # db:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=YourStrong!Passw0rd
  #   ports:
  #     - "1433:1433"
  #   healthcheck:
  #     test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q 'SELECT 1'"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3 